version: "3"
services:
  streamlit:
    build: .
    working_dir: /usr/src/app/src
    command: "streamlit run main.py --logger.level=error"
    volumes:
      - "./src:/usr/src/app/src"
    networks:
      - nginx-proxy_frontend
    restart: always
    environment:
      VIRTUAL_HOST: csv.aeducar.es
      LETSENCRYPT_HOST: csv.aeducar.es
      LETSENCRYPT_EMAIL: jesuslopezdeleyva@gmail.com

networks:
  nginx-proxy_frontend:
    external: true

