version: "3"
services:
  streamlit:
    build: .
    command: "streamlit run src/main.py --logger.level=error"
    volumes:
      - "./src:/usr/src/app/src"
    networks:
      - soporte_catedu_aragon_frontend
    environment:
      VIRTUAL_HOST: csv.aeducar.es
      LETSENCRYPT_HOST: csv.aeducar.es
      LETSENCRYPT_EMAIL: jesuslopezdeleyva@gmail.com

networks:
  soporte_catedu_aragon_frontend:
    external: true
