version: "3"
services:
  streamlit:
    build: .
    working_dir: /usr/src/app/src
    command: "streamlit run main.py --logger.level=error"
    volumes:
      - "./src:/usr/src/app/src"
    ports:
      - "8501:8501"